version: '3'

services:
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - django
