# Generated by Django 5.0.1 on 2024-04-07 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='otp_code',
        ),
    ]
