# Dockerfile for Django
FROM python:3.11.9

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /core

# Install dependencies
COPY requirements.txt /core/
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy project files
COPY . /core/
