# Generated by Django 5.0.1 on 2024-04-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pic',
            field=models.ImageField(upload_to='cateogry_img'),
        ),
    ]
