# Generated by Django 5.0.1 on 2024-04-18 18:46

import Product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_product_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='image',
            field=models.ImageField(upload_to=Product.models.image_upload_path),
        ),
    ]
